//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAzure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int ID { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> CourseFee { get; set; }
        public string Duration { get; set; }
        public Nullable<int> NumberOfEnrollments { get; set; }
        public string EnrolledStudents { get; set; }
        public string CourseStartTime { get; set; }
        public string CourseEndTime { get; set; }
        public string Context { get; set; }
    }
}
