//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testAzure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TeacherName { get; set; }
        public string Subject { get; set; }
    }
}
